name: codemd
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.10.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  markdown: ^7.2.2
  flutter_markdown: ^0.7.4
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_svg: ^2.0.10
  http: ^1.2.2
  crypto: ^3.0.5
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  flutter_math_fork: ^0.7.2
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0
  uuid: ^4.5.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  flutter_hooks: ^0.20.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  flutter_inappwebview: ^6.0.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^10.1.4
  google_mobile_ads: ^5.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2d2d2d"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_foreground_inset: 16
flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/mermaid/mermaid.html
  - assets/mermaid/mermaid.min.js
